/// <reference lib="webworker" />

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'
import { clientsClaim } from 'workbox-core'

declare const self: ServiceWorkerGlobalScope & { __WB_MANIFEST: any }

const sw = self

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST)
cleanupOutdatedCaches()

// Take control of all clients immediately
sw.skipWaiting()
clientsClaim()

// ── PUSH NOTIFICATION HANDLER ───────────────────────────────────────────────
sw.addEventListener('push', (event: PushEvent) => {
  if (!event.data) return

  try {
    const data = event.data.json()
    const title = data.title || 'Obel'
    const options: any = {
      body: data.body || 'Timer complete!',
      icon: '/obel.png',
      badge: '/obel.png',
      tag: data.tag || 'obel-timer',
      vibrate: [200, 100, 200, 100, 200, 100, 200],
      data: {
        url: sw.location.origin + (data.tag === 'obel-timer' ? '/pomodoro' : '/')
      }
    }

    event.waitUntil(sw.registration.showNotification(title, options))
  } catch (err) {
    console.error('Push notification error:', err)
  }
})

// Handle notification click
sw.addEventListener('notificationclick', (event: NotificationEvent) => {
  event.notification.close()
  const urlToOpen = event.notification.data?.url || sw.location.origin

  event.waitUntil(
    sw.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Check if there is already a window open and focus it
      for (const client of windowClients) {
        const c = client as WindowClient
        if (c.url === urlToOpen && 'focus' in c) {
          return c.focus()
        }
      }
      // If no window is open, open a new one
      if (sw.clients.openWindow) {
        return sw.clients.openWindow(urlToOpen)
      }
    })
  )
})
